config/routes.rb
Rails.application.routes.draw do
  resources :repositories do
    resources :issues, only: [:show]
    resources :projects, only: [:index, :show]
  end
  root 'projects#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/application.yml"
  namespace Rails.env
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :restrict_remote_ip
  before_action :authenticate_basic

  private

  def restrict_remote_ip
    if ENV['PERMIT_ADDRESS_PATTERNS'].present?
      matched = ENV['PERMIT_ADDRESS_PATTERNS'].split(',').any? do |permit_address_pattern|
        request.remote_ip.match permit_address_pattern
      end
      render plain: 'Service Unavailable', status: 503 unless matched
    end
  end

  def authenticate_basic
    if ENV['BASIC_USER'] && ENV['BASIC_PASS']
      authenticate_or_request_with_http_basic do |user, pass|
        user == ENV['BASIC_USER'] && pass == ENV['BASIC_PASS']
      end
    end
  end
end

app/controllers/concerns/github_accessible.rb
module GithubAccessible
  extend ActiveSupport::Concern

  included do
    before_action :set_github_client
    before_action :set_repositories
    before_action :set_current_repository
  end

  private

  def set_github_client
    @github_client = Octokit::Client.new(access_token: ENV['GITHUB_ACCESS_TOKEN'])
    @github_client.auto_paginate = true
  end

  def set_repositories
    @repositories = @github_client.repositories.select do |repository|
      return true if ENV['REPOSITORIES'].blank?
      ENV['REPOSITORIES'].split(',').include?(repository.name)
    end
  end

  def set_current_repository
    @current_repository = @repositories.find do |repository|
      repository.full_name == params[:repository_id]
    end || @repositories.first
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  include GithubAccessible

  def show
    @issue = @github_client.issue(@current_repository.full_name, params[:id])
    @comments = @github_client.issue_comments(@current_repository.full_name, params[:id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include GithubAccessible

  def index
    @projects = @github_client.projects(@current_repository.full_name)
    @issues = @github_client.issues(@current_repository.full_name)
  end

  def show
    @project = @github_client.project(params[:id])
    project_columns = @github_client.project_columns(params[:id])
    @columns = Parallel.map(project_columns, in_threads: project_columns.size) do |column|
      column_cards = @github_client.column_cards(column.id)
      cards = Parallel.map(column_cards, in_threads: column_cards.size) do |card|
        if card.content_url.present?
          issue_number = card.content_url.split('/').last
          issue = @github_client.issue(@current_repository.full_name, issue_number)
        end
        [card, issue]
      end.compact.to_h
      [column, cards]
    end.compact.to_h
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
  def markdown(text)
    unless @markdown
      renderer = Redcarpet::Render::HTML.new
      @markdown = Redcarpet::Markdown.new(renderer, tables: true)
    end
    @markdown.render(text).html_safe
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def state2icon(state)
    case state
      when 'open'
        content_tag('i', nil, class: 'fa fa-check-circle text-success')
      when 'closed'
        content_tag('i', nil, class: 'fa fa-check-circle text-danger')
    end
  end

  def badge_to(issue)
    if issue.pull_request
      content_tag('span', 'pull request', class: 'badge badge-primary')
    else
      content_tag('span', 'issue', class: 'badge badge-secondary')
    end
  end
end

app/views/application/_footer.html.erb
<footer class="pt-5">
  <p class="text-center">Copyright © 2018 <%= Settings.site.name %></p>
</footer>

app/views/application/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light">
    <%= link_to root_path, class: 'navbar-brand' do %>
      <%= image_tag 'github-logo.png', class: 'rounded-circle', width: 30, style: 'vertical-align:top;' %>
      <%= Settings.site.name %>
    <% end %>
    <% if @repositories %>
      <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="ナビゲーションの切替">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav mr-auto">
          <% @repositories.each do |repository| %>
            <li class="nav-item">
              <%= link_to repository.name, repository_projects_path(repository.full_name), class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </nav>
</header>

app/views/issues/show.html.erb
<h1>
  <%= @issue.title %> <span class="small"><%= link_to "##{@issue.number}", @issue.html_url, target: '_blank' %></span>
</h1>
<div class="row">
  <div class="col-12">
    <% @issue.labels.each do |label| %>
      <span class="badge" style="background-color: <%= "\##{label.color}" %>">
        <%= label.name %>
      </span>
    <% end %>
  </div>
</div>
<div class="row mt-2">
  <div class="col-12">
    <%= state2icon @issue.state %> <%= @issue.user.login %> opened this issue <%= time_ago_in_words @issue.created_at %>
    ago <%= @issue.comments %> comments
  </div>
</div>
<div class="row mt-2">
  <div class="col-md-1 d-none d-md-block">
    <div class="text-center">
      <%= image_tag @issue.user.avatar_url, class: 'rounded', width: 60 %>
    </div>
  </div>
  <div class="col-12 col-md-11">
    <div class="card">
      <div class="card-body">
        <div class="card-title">
          <small><%= @issue.user.login %> commented <%= time_ago_in_words @issue.created_at %> ago</small>
        </div>
        <div class="card-text edit-content">
          <%= markdown @issue.body %>
        </div>
      </div>
    </div>
  </div>
</div>
<% @comments.each do |comment| %>
  <div class="row mt-2">
    <div class="col-md-1 d-none d-md-block">
      <div class="text-center">
        <%= image_tag comment.user.avatar_url, class: 'rounded', width: 60 %>
      </div>
    </div>
    <div class="col-12 col-md-11">
      <div class="card">
        <div class="card-body">
          <div class="card-title">
            <small><%= comment.user.login %> commented <%= time_ago_in_words comment.created_at %> ago</small>
          </div>
          <div class="card-text edit-content">
            <%= markdown comment.body %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= Settings.site.name %></title>
  <meta name="viewport" content="width=360,initial-scale=1">
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>

<body>
<%= render 'header' %>
<div class="mb-auto">
  <div class="container">
    <%= yield %>
  </div>
</div>
<%= render 'footer' %>
</body>
</html>

app/views/projects/_issue_card_body.html.erb
<div class="card-body">
  <div class="d-flex">
    <h5 class="card-title">
      <%= state2icon issue.state %>
      <%= link_to issue.title, repository_issue_path(@current_repository.full_name, issue.number) %>
    </h5>
    <% unless issue.comments.zero? %>
      <div class="align-middle ml-auto text-nowrap">
        <i class="fa fa-comment-o"></i>
        <span><%= issue.comments %></span>
      </div>
    <% end %>
  </div>
  <small>
    #<%= issue.number %> opened by <%= issue.user.login %>
  </small>
  <div class="card-text container">
    <p>
      <%= card.note %>
    </p>
    <div class="row">
      <div class="col">
        <% issue.labels.each do |label| %>
                        <span class="badge" style="background-color: <%= "\##{label.color}" %>">
                          <%= label.name %>
                        </span>
        <% end %>
      </div>
      <ul class="col-auto">
        <% issue.assignees.each do |assignee| %>
          <%= image_tag assignee.avatar_url, class: 'rounded-circle', width: 25 %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/projects/_note_card_body.html.erb
<div class="card-body">
  <div class="card-text container">
    <p><%= card.note %></p>
  </div>
</div>

app/views/projects/index.html.erb
<h1><%= @current_repository.full_name %></h1>
<div class="row">
  <div class="col-12">
    <div class="">
      <div class="d-flex">
        <h2>Issues</h2>
        <span class="badge badge-secondary my-auto ml-2"><%= @issues.size %></span>
      </div>
      <table class="table table-hover">
        <tbody>
        <% @issues.each do |issue| %>
          <tr>
            <td><%= badge_to(issue) %></td>
            <td>
              <div class="d-flex">
                <%= link_to issue.title, repository_issue_path(@current_repository.full_name, issue.number), class: 'd-block' %>
                <% issue.labels.each do |label| %>
              <span class="badge my-auto ml-1" style="background-color: <%= "\##{label.color}" %>">
                <%= label.name %>
              </span>
                <% end %>
              </div>
              <small>
                #<%= issue.number %> opened this issue <%= time_ago_in_words issue.created_at %>
                by <%= issue.user.login %>
              </small>
            </td>
            <td class="align-middle text-nowrap">
              <% issue.assignees.each do |assignee| %>
                <%= image_tag assignee.avatar_url, class: 'rounded', width: 30 %>
              <% end %>
            </td>
            <td class="align-middle text-nowrap">
              <% unless issue.comments.zero? %>
                <i class="fa fa-comment-o"></i>
                <span><%= issue.comments %></span>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<h1><%= @project.name %></h1>
<div class="row justify-content-center">
  <% @columns.each do |column, cards| %>
    <div class="col-12 col-md">
      <h2>
        <span class="rounded-circle p-0 small text-center d-inline-block mr-2" style="width:2rem;height:2rem;line-height:2rem;background-color:whitesmoke;"><%= cards.size %></span><%= column.name %>
      </h2>
      <ul class="list-unstyled">
        <% cards.each do |card, issue| %>
          <li>
            <div class="card mb-2">
              <% if issue.present? %>
                <%= render 'issue_card_body', card: card, issue: issue %>
              <% else %>
                <%= render 'note_card_body', card: card %>
              <% end %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>